const data = {
  JAAnime: {
    meta: {
      longName: "Japanese Anime",
      externalURL: "test",
      field: {
        description: {
          field0: "number",
          field1: "hiragana",
          field2: "kanji",
          field3: "type",
          field4: "meaning",
          field5: "unused1",
          field6: "unused2",
          field7: "unused3",
        },
        type: {
          field0: "text",
          field1: "text",
          field2: "text",
          field3: "text",
          field4: "text",
          field5: "text",
          field6: "picture",
          field7: "audio",
        },
        initialVisibility: {
          field0: "shown",
          field1: "shown",
          field2: "hidden",
          field3: "hidden",
          field4: "hidden",
          field5: "hidden",
          field6: "hidden",
          field7: "hidden",
        },
      },
    },
    content: [
      {
        field0: "content0",
        field1: "content1",
        field2: "content2",
        field3: "content3",
        field4: "content4",
        field5: "content5",
        field6: "content6",
        field7: "content7",

      },
      {
        field0: "content0",
        field1: "content1",
        field2: "content2",
        field3: "content3",
        field4: "content4",
        field5: "content5",
        field6: "content6",
        field7: "content7",
      },
    ],
  },
  JASimpleNouns: {
    meta: {
      longName: "Japanese Simple Nouns",
      externalURL: "test",
      field: {
        name: {
          field0: "number",
          field1: "hiragana",
          field2: "kanji",
          field3: "type",
          field4: "meaning",
          field5: "unused1",
          field6: "unused2",
          field7: "unused3",
        },
        type: {
          field0: "picture",
          field1: "text",
          field2: "text",
          field3: "text",
          field4: "text",
          field5: "text",
          field6: "picture",
          field7: "audio",
        },
        initialVisibility: {
          field0: "shown",
          field1: "shown",
          field2: "hidden",
          field3: "hidden",
          field4: "hidden",
          field5: "hidden",
          field6: "hidden",
          field7: "hidden",
        },
      },
    },
    content: [
      {
        field0: "content0",
        field1: "content1",
        field2: "content2",
        field3: "content3",
        field4: "content4",
        field5: "content5",
        field6: "content6",
        field7: "content7",
      },
      {
        field0: "content0",
        field1: "content1",
        field2: "content2",
        field3: "content3",
        field4: "content4",
        field5: "content5",
        field6: "content6",
        field7: "content7",
      },
    ],
  }
};
